export default {
    products: [
        {
            _id: '1',
            name: 'White Chocolate Mocha',
            category: 'Coffee',
            image: 'images/product-1.jpg',
            price: 10,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Caramel Macchiato',
            category: 'Coffee',
            image: 'images/product-2.jpg',
            price: 5,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Caramel Frappuccino',
            category: 'Coffee',
            image: 'images/product-3.jpg',
            price: 5,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Chai Latte',
            category: 'Coffee',
            image: 'images/product-4.jpg',
            price: 5,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Cold Brew with Dark Cocoa Almondmilk Foam',
            category: 'Coffee',
            image: 'images/product-5.jpg',
            price: 5,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Caffè Latte',
            category: 'Coffee',
            image: 'images/product-6.jpg',
            price: 5,
            brand: 'Starbucks',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }
    ]
}
